### ISSUE TITLE
Compiling with WinAVR

### ISSUE THREAD

**Issue by germainm** [andreacampanella/XenoGC328#2]
I tried compile XenoAT with WinAVR but problem with avr-objcopy.exe

say the application was unable to start correct (0xc00000142). Click OK to close the application

Could you provide the compiled hex for atmega328p ?

Provided hex in the directories are identical to atmega8, I guess it need to be recompiled.

Thanks for your help

**Comment by andreacampanella** [comment]
Sorry,I have no idea, I use avrdude on Linux...

**Comment by pudrik** [comment]
Code might be working but seem to be missing fuse settings so its hard to test whats wrong when troubleshooting. as original atmega8 only has HFUSE/LFUSE and 328 har also EFUSE not to mention that the values aren't compatible. So Fuse settings in instructions or makefile ??? Also avrdude parms seem to be wrong when executing make program. "-i hexfile" isnt valid proper syntax would be "-U flash:w:hexfile:m" and as mentioned missing fuse data.

**Comment by andreacampanella** [comment]
I honestly left the original Arduino fuses : 

uno.bootloader.low_fuses=0xff
uno.bootloader.high_fuses=0xde
uno.bootloader.extended_fuses=0x05

**Comment by pudrik** [comment]
Just to check that you are aware that 0x05 is an invalid value for efuse on a 328 it probably should be 0xFD and the other settings would set the chip to operate using an external 8mhz crystal (Most arduinos use 16 / 20 nowdays) and the original atmega8 is configured to run on 8mhz Internal.
Have you actually burned the code / fuses and tested it on a machine?

**Comment by andreacampanella** [comment]
I did it but long time ago, I'm sorry , I don't have a GameCube anymore..
